version: "3.8"

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  aoonjai-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/aoonjai-api
    command: npm run start
    working_dir: /usr/src/aoonjai-api
    ports:
      - "8000:8000"
    environment:
       - CHOKIDAR_USEPOLLING=true
